[package]
name = "boop-app"
version = "0.1.0"
edition = "2024"

[dependencies]
boop-common.workspace = true
slint.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
slint = { workspace = true, features = ["backend-android-activity-06"] }

[build-dependencies]
slint-build.workspace = true