import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <int> counter: 0;
    in property <string> fizzbuzz: "";
    callback increment;
    callback decrement;

    VerticalLayout {
        padding: 20px;
        alignment: center;
        spacing: 20px;
        
        Text {
            text: "Hello World!";
        }

        Text {
            text: "Counter: \{root.counter}";
        }

        Text {
            text: fizzbuzz;
        }

        HorizontalLayout {
            padding: 20px;
            spacing: 20px;
            Button {
                text: "+";
                clicked => {
                    root.increment();
                }
            }
            Button {
                text: "-";
                clicked => {
                    root.decrement();
                }
            }
        }
    }
}